name: Redeploying to Production server

on:
  push:
    branches:
      - "production"

jobs:
  redeploy_everything_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRODUCTION_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd turbo-http-ws-next-pipeline/
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

            pnpm install
            pnpm run build

            cd apps/http-server
            pm2 restart http-server || pm2 start npm --name "http-server" -- start
            cd ../..

            cd apps/web
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
            cd ../..

            cd apps/ws-server
            pm2 restart ws-server || pm2 start npm --name "ws-server" -- start


            echo "All Services are deployed succesfully."
